server:
  port: 8082

spring:
  application:
    name: customer
  zipkin:
    base-url: http://localhost:9411/

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #default address